
import mongoose from "mongoose";
import dotenv from "dotenv";
import Advisory from "./models/Advisory.js";
import path from "path";
import { fileURLToPath } from "url";

// Config for dotenv
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, ".env") });

const runDebug = async () => {
    console.log("🐛 Starting MongoDB Write Debug...");
    const uri = process.env.MONGO_URI || process.env.MONGODB_URI;
    console.log("Checking MongoDB URI:", uri ? "Defined ✅" : "Missing ❌");

    if (!uri) {
        console.error("❌ Error: MONGO_URI or MONGODB_URI is not set.");
        process.exit(1);
    }

    try {
        await mongoose.connect(uri);
        console.log("✅ MongoDB Connected.");

        // Create a dummy advisory
        const testAdvisory = new Advisory({
            title: "Test Crop " + Date.now(),
            description: "This is a test advisory generated by debug_mongo.js",
            category: "Debug",
            path: "/debug-test-" + Date.now()
        });

        console.log("Attempting to save document...");
        const saved = await testAdvisory.save();
        console.log("✅ Save Successful!");
        console.log("Saved ID:", saved._id);
        console.log("Collection Name should be:", Advisory.collection.name);

        // Verify it exists
        const found = await Advisory.findById(saved._id);
        if (found) {
            console.log("✅ Verification Read Successful: Document found in DB.");
        } else {
            console.log("❌ Verification Read Failed: Document NOT found after save.");
        }

        // Cleanup
        await Advisory.findByIdAndDelete(saved._id);
        console.log("✅ Cleanup: Test document deleted.");

    } catch (error) {
        console.error("❌ Debug Operation Failed:", error);
    } finally {
        await mongoose.disconnect();
        console.log("🔌 Disconnected.");
        process.exit(0);
    }
};

runDebug();
